### ISSUE TITLE
`if-let` and `when-let`

### ISSUE THREAD

**Issue by akirak** [alphapapa/frame-purpose.el#3]
Crazily, `if-let` and `when-let`, which were introduced in Emacs 25, have been renamed to `if-let*` and `when-let*` respectively in Emacs 26 and the old functions **no longer exist** in newer versions. Therefore you have to use `if-let` in Emacs 25 and `if-let*` in Emacs 26. 

A possible workaround is to define aliases:

```emacs-lisp
(eval-and-compile
  (when (version< emacs-version "26")
    (with-no-warnings
      (defalias 'when-let* #'when-let)
      (function-put #'when-let* 'lisp-indent-function 1)
      (defalias 'if-let* #'if-let)
      (function-put #'if-let* 'lisp-indent-function 2))))
```

**Comment by alphapapa** [comment]
Thanks.  This is really annoying.  Having every Emacs package that's used these functions since Emacs 25 reimplement these aliases seems like a bad idea, but I guess the choice is to do that or use `-when-let` and `-if-let`.

However, isn't it the case that those macros are marked as obsolete, which means they still exist in Emacs 26 but raise warnings upon compilation?  If so, we could simply ignore the warnings...  :)

**Comment by akirak** [comment]
Really? Actually, I haven't used Emacs 26 yet, so I might have misunderstood the information. I'm sorry for mis-reporting this issue.

**Comment by alphapapa** [comment]
No, you haven't done anything wrong.  I haven't used Emacs 26 yet either, but I see that other projects, like  https://github.com/raxod502/el-patch/issues/17, have had to deal with this in the same way.  I appreciate your reminding me.

**Comment by akirak** [comment]
I see. Thanks. I could learn about the compatibility issue. As a Japanese guy, I may tend to say sorry too often.

**Comment by zenspider** [comment]
please close. Seems like emacs 27 has all 4 functions and nothing has been obsoleted.

**Comment by alphapapa** [comment]
@zenspider I don't mind if someone follows up on old issues, but since it's not your repo, it would be more polite if you didn't tell others what to do.  ;)
